version: '3.3'
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  server:
    build: ./server
    command: npm start
    environment:
      - CONFIG=dev
    volumes:
      - ./server:/usr/src/server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  client:
    build: ./client
    command: npm start
    environment:
    - CONFIG=dev
    volumes:
    - ./client:/usr/src/client
    ports:
    - "3000:3000"
    depends_on:
    - server