version: '3.3'
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  server:
    build: .
    command: npm start
    environment:
      - CONFIG=dev
    volumes:
      - .:/usr/src/server
    ports:
      - "5000:5000"
    depends_on:
      - mongo